version: '2'

services:
  db:
    image: jubilee2/rpi-mariadb:v10.4.19
    container_name: "my-mysqldb"
    volumes:
      - ./db:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: x#R?2tR!
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  adminer:
    image: adminer:4.7.7
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - "db"
