version: "2"
services:
    mongodb:
        image: mongo:latest
        container_name: "my-mongo"
        restart: always
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./db:/data/db
        ports:
            - 27017:27017

